# Config file for IGoR wrapper (launch_igor.py script)

# Database specs
species: "human"
# Type of cell (can be "IgM" or "IgG")
cellType: "IgG"
# Type of chain (can be "HC", "KC" or "LC")
chainType: "HC"
# Patient cohort (can be chosen among ['healthy_control', 'hiv1', 'hcv']; for other possible regroupings of donors, please check the script '')
cohort: "healthy_control"
produc: "P"

# SHM reference model. Can be chosen among:
# - "none" : no SHMs, only for heavy naive seqs
# - "default" : default model for heavy memory seqs
# - "indip" : indipendent SHM model
# - "add5mer" : additive SHM Nmer model
# - "full5mer": full SHM Nmer model (like S5F)
SHMmodel: "add5mer"

# Quality filters (referred to which sequence to load)
filter_by_UMI: True
UMI_thr: 3
filter_by_indels: True
edges_trimmed: True
n_l: 27
n_r: 3

wk_dir: "./"
input_dir: "./datasets/"
final_template_dir: "./../templates/igor_models/inferred/"

# IGoR root
mainIgorDir: "/home/lupo/IGoR/igor_1-4-1/"
defaultIgorTemplates: "./../templates/igor_models/default/"

# IGoR main steps (order is fixed, but single steps can be executed or not)
modelConstruction: False
seqRead: True
alignment: True
filter: False
inferGenModel: True
evalGenModel: True
generateSeqs: False

# Gathering together igBlast and IGoR results for ig
igAnalysisFinalSummary: True

# main flags
initInferBySHMindip: False
useLastInferred: True
useLastEvaluated: True
bestGeneOnly: False

# IGoR internal parameters
N_cores: 40
L_thresh: '1e-300'
N_iters: 10
align_thr: 250
P_ignore: 0.001
N_scen: 10
V_thresh: 100.0
D_thresh: 15.0
J_thresh: 15.0
gap_penalty: 50.0
# N_subsampling can be 'None' (if not needed) or an integer value
N_subsampling: 'None'
N_generated: 10000
# Alignment offset parameters
v_low: -400
v_high: 400
d_low: 200
d_high: 350
j_low: 210
j_high: 400
