# Config file for Ig annotation (ig_annotation.py script)

# General specs (relative paths are supported)
wkdir: "./"
inputdir: "./sequences/"
input_file_prefix: "bnabs_seqs"

# igBlast paths
#igBlastExec: "/home/lupo/igBlast/ncbi-igblast-1.13.0/bin/igblastn"
igBlastExec: "igblastn"
#blast_database: "/home/lupo/igBlast/blast_database/"
blast_database: "./../templates/"

# Script step n. 1 (pre-processing of input files)
preProcessFiles: True

# Script step n. 2 (igBlast running)
runIgBlast: True

# Script step n. 3 (parsing of igBlast output)
parseIgBlast: True

# Script step n. 4 (writing of final sequence files, possibly reverted and trimmed)
produceFinalFiles: True

# Species
species: "Homo_Sapiens"

# Type of cell (can be "IgM" or "IgG")
cellType: "IgG"

# Type of chain (can be "heavy", "kappa" or "lambda")
chainType: "heavy"

# Trimming parameters
# n_l is 2 for "heavy" and "kappa", 27 for "lambda"
n_l: 2
n_r: 2
