# Config file for IGoR wrapper (launch_igor.py script)

wk_dir: "./"
input_dir: "./sequences/"
input_file_prefix: "bnabs_seqs"

# Database specs (quality filters included - referred to bnabs to analyze)
species: "human"
chainType: "HC"
filter_by_indels: True
edges_trimmed: True
# n_l is 2 for "HC" and "KC", 27 for "LC"
n_l: 2
n_r: 2

# Model specs (some quality filters included - referred to IGoR models to use for evaluating bnabs)
UMI_thr: 3
# If a single model has to be loaded for bnabs evaluation
singleModel: True
# General model ('cohortWide_P' is the one used for manuscript main figures)
produc: "cohortWide_P"
# Patient cohort (can be chosen among ['healthy_control', 'hiv1', 'hcv']; for further possible stratifications of the 'hiv1' cohort, please check the README file or the manuscript)
cohort: "healthy_control"
# SHM model ('add5mer' is the one used for manuscript main figures)
SHMmodel: "add5mer"

# Otherwise, the dataset of bnabs can be evaluated according to several different models; undesired items in the following lists can be commented out
producs:
  - "standard_NP"
  - "cohortWide_NP"
  - "cohortWide_P"
cohorts:
  - "healthy_control"
  - "hiv1"
  - "hcv"
#  - "hiv1_non_neutralizers"
#  - "hiv1_weak_neutralizers"
#  - "hiv1_intermediate_neutralizers"
#  - "hiv1_top_neutralizers"
#  - "hiv1_art_off"
#  - "hiv1_art_on"
SHMmodels:
  - "add5mer"
  - "full5mer"

# IGoR paths
igorExec: "/home/lupo/IGoR/igor_1-4-1/igor_src/igor"
#igorExec: "igor"
defaultIgorTemplates: "./../templates/igor_models/default/"
#inferredIgorTemplates: "/home/lupo/BCR_Klein_data/IGoR_models/"
inferredIgorTemplates: "./../templates/igor_models/inferred/"

# IGoR main steps (order is fixed, but single steps can be executed or not)
seqRead: True
alignment: True
evalGenModel: True

# Gathering together igBlast and IGoR results for bnabs
bnabAnalysisFinalSummary: True

# main flags
# Default value for bestGeneOnly is false for V, D and J
bestGeneOnly: False
# Default value for bestAlignOnly is true for V and J, and false for D
bestAlignOnly: True
useRegularizedModel: True

# IGoR internal parameters
N_cores: 1
L_thresh: '1e-307'
N_iters: 10
align_thr: 250
P_ignore: '1e-8'
N_scen: 10
V_thresh: 30.0
D_thresh: 15.0
J_thresh: 15.0
gap_penalty: 50.0
# N_subsampling can be 'None' (if not needed) or an integer value
N_subsampling: 'None'
# Alignment offset parameters
v_low: -400
v_high: 400
d_low: 200
d_high: 350
j_low: 210
j_high: 400
