# Config file for IGoR wrapper (launch_igor.py script)

wkdir: "./"
#inputdir: "/home/lupo/bnabs_Klein/latest_bnabs_list"
input_dir: "./sequences/"
#input_file_prefix: "all_new_bnabs_seqs"
input_file_prefix: "bnabs_seqs"
#model_dir: "/home/lupo/BCR_Klein_data/IGoR_models/"
model_dir: "./../templates/igor_models/inferred/"

# Database specs (quality filters included - referred to bnabs to analyze)
species: "human"
chainType: "HC"
filter_by_indels: True
edges_trimmed: True
n_l: 3
n_r: 3

# Model specs (some quality filters included - referred to IGoR models to use for evaluating bnabs)
UMI_thr: 3
# If a single model has to be loaded
singleModel: True
cohort: "healthy_all"
produc: "cohortWide_P"
SHMmodel: "full5mer"
# Otherwise, the dataset can be evaluated according to a set of different models
# Undesired items in the following lists can be commented out:
producs:
  - "standard"
  - "cohortWide_NP"
  - "cohortWide_P"
cohorts:
  - "healthy"
  - "hiv1_viremic"
  - "hiv1_on_art"
  - "hcv"
  - "hiv1_top"
  - "healthy_topControl"
  - "healthy_all"
  - "hiv1_all"
  - "hiv1_non_neutralizers"
  - "hiv1_weak_neutralizers"
  - "hiv1_intermediate_neutralizers"
  - "hiv1_top_neutralizers"
  - "hiv1_ART_OFF"
  - "hiv1_ART_ON"
SHMmodels:
  - "add5mer"
  - "full5mer"

# IGoR root
mainIgorDir: "/home/lupo/IGoR/igor_1-4-1/"

# IGoR main steps (order is fixed, but single steps can be executed or not)
seqRead: False
alignment: False
evalGenModel: False

# Gathering together igBlast and IGoR results for bnabs
bnabAnalysisFinalSummary: True

# main flags
bestGeneOnly: False

# IGoR internal parameters
N_cores: 1
L_thresh: '1e-307'
N_iters: 10
align_thr: 250
P_ignore: 0.00001
N_scen: 10
V_thresh: 100.0
D_thresh: 15.0
J_thresh: 15.0
gap_penalty: 50.0
# N_subsampling can be 'None' (if not needed) or an integer value
N_subsampling: 'None'
# Alignment offset parameters
v_low: -400
v_high: 400
d_low: 200
d_high: 350
j_low: 210
j_high: 400